import type { TerpeneCompound, TerpeneFamily } from "./types";

export const terpeneFamilies: TerpeneFamily[] = [
  { id: "hemiterpene", label: "Hemiterpenes", carbonCount: "C5", isopreneUnits: "1", summary: "Five-carbon members of the terpene family." },
  { id: "monoterpene", label: "Monoterpenes", carbonCount: "C10", isopreneUnits: "2", summary: "Ten-carbon compounds commonly derived from geranyl diphosphate." },
  { id: "sesquiterpene", label: "Sesquiterpenes", carbonCount: "C15", isopreneUnits: "3", summary: "Fifteen-carbon compounds commonly derived from farnesyl diphosphate." },
  { id: "diterpene", label: "Diterpenes", carbonCount: "C20", isopreneUnits: "4", summary: "Twenty-carbon compounds with broad structural and biological diversity." },
  { id: "sesterterpene", label: "Sesterterpenes", carbonCount: "C25", isopreneUnits: "5", summary: "Twenty-five-carbon terpenes found across specialized natural-product pathways." },
  { id: "triterpene", label: "Triterpenes", carbonCount: "C30", isopreneUnits: "6", summary: "Thirty-carbon terpenes that include squalene- and sterol-related pathways." },
  { id: "tetraterpene", label: "Tetraterpenes", carbonCount: "C40", isopreneUnits: "8", summary: "Forty-carbon compounds that include carotenoid-related natural products." },
  { id: "polyterpene", label: "Polyterpenes", carbonCount: ">C40", isopreneUnits: "many", summary: "Long-chain terpene polymers assembled from repeated isoprene units." },
];

export const terpeneSeedCompounds: TerpeneCompound[] = [
  {
    slug: "beta-myrcene",
    name: "β-Myrcene",
    aliases: ["myrcene", "beta-myrcene"],
    terpeneClass: "monoterpene",
    structureFamily: "acyclic",
    functionalClass: "hydrocarbon",
    formula: "C10H16",
    molecularWeight: 136.24,
    pubchemCid: 31253,
    casNumber: "123-35-3",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["earthy", "herbal", "musky"],
    naturalSources: ["Cannabis", "hops", "bay", "lemongrass"],
    cannabisOccurrence: "documented",
    cannabisContext: "Frequently detected in cannabis inflorescence volatile profiles, but abundance varies by genotype, sample position, maturity, handling, and analytical method.",
    geneticsContext: "Functionally characterized cannabis terpene synthases can produce myrcene. One synthase can produce multiple products, so a single gene marker is not a complete aroma prediction.",
    cultivarContext: "Use repeated laboratory profiles and cultivar provenance. A cultivar name alone does not guarantee a fixed myrcene percentage.",
    researchGuardrail: "Do not convert myrcene abundance into a guaranteed human effect. Biological-effect claims require evidence grading separate from aroma chemistry.",
    viewNotes: {
      aroma: "Earthy, herbal, and musky descriptors are common sensory shorthand, but aroma emerges from mixtures and odor thresholds.",
      chemistry: "An acyclic C10 monoterpene hydrocarbon.",
      biosynthesis: "Built from the monoterpene precursor pool centered on GPP and terpene-synthase activity.",
      genetics: "Cannabis terpene-synthase variation can influence myrcene production, but expression and environment also shape the final profile.",
      cultivars: "Compare measured sample distributions rather than assigning one permanent value to a cultivar name.",
    },
    sourceIds: ["THC-V13", "PUBCHEM"],
  },
  {
    slug: "limonene",
    name: "Limonene",
    aliases: ["d-limonene", "l-limonene"],
    terpeneClass: "monoterpene",
    structureFamily: "monocyclic",
    functionalClass: "hydrocarbon",
    formula: "C10H16",
    molecularWeight: 136.24,
    pubchemCid: 22311,
    casNumber: "138-86-3",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["citrus", "lemon", "orange", "fresh"],
    naturalSources: ["Cannabis", "citrus peel", "juniper", "mint"],
    cannabisOccurrence: "documented",
    cannabisContext: "Detected in cannabis volatile profiles. Chiral forms can differ in odor, and routine non-chiral testing may combine them.",
    geneticsContext: "Cannabis limonene synthases are part of a broader terpene-synthase system where enzyme product mixtures and expression levels matter.",
    cultivarContext: "Citrus-labeled cultivars should be verified analytically because citrus aroma can also involve aldehydes, esters, sulfur compounds, and other terpenes.",
    researchGuardrail: "A citrus descriptor or elevated limonene result does not establish a therapeutic outcome.",
    viewNotes: {
      aroma: "Often associated with citrus-like notes, but it is only one contributor to citrus aroma.",
      chemistry: "A cyclic C10 monoterpene hydrocarbon with stereochemical forms.",
      biosynthesis: "Produced from GPP through terpene-synthase catalysis.",
      genetics: "Genotype and terpene-synthase expression influence production; storage and oxidation alter the measured profile.",
      cultivars: "Rank cultivars by repeated measured profiles, not by marketing descriptors.",
    },
    sourceIds: ["THC-V13", "PUBCHEM"],
  },
  {
    slug: "alpha-pinene",
    name: "α-Pinene",
    aliases: ["alpha-pinene"],
    terpeneClass: "monoterpene",
    structureFamily: "bicyclic",
    functionalClass: "hydrocarbon",
    formula: "C10H16",
    molecularWeight: 136.24,
    pubchemCid: 6654,
    casNumber: "80-56-8",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["pine", "resin", "fresh", "woody"],
    naturalSources: ["Cannabis", "pine", "rosemary", "sage"],
    cannabisOccurrence: "documented",
    cannabisContext: "A documented cannabis monoterpene that should be distinguished from β-pinene and from stereochemical variants when the analytical method permits.",
    geneticsContext: "Pinene can arise from functionally characterized terpene synthases; product identity cannot be inferred from sequence similarity alone.",
    cultivarContext: "Use alpha- and beta-pinene as separate analytes when comparing cultivar profiles.",
    researchGuardrail: "Pine-like aroma is not a quantitative assay and does not establish a human effect.",
    viewNotes: {
      aroma: "Pine and resin descriptors are common but not unique to α-pinene.",
      chemistry: "A bicyclic C10 monoterpene hydrocarbon.",
      biosynthesis: "Produced from GPP through cyclization reactions catalyzed by terpene synthases.",
      genetics: "Terpene-synthase genotype, expression, trichome development, and environment all influence the result.",
      cultivars: "Profile comparisons should keep α-pinene separate from β-pinene.",
    },
    sourceIds: ["THC-V13", "PUBCHEM"],
  },
  {
    slug: "beta-pinene",
    name: "β-Pinene",
    aliases: ["beta-pinene"],
    terpeneClass: "monoterpene",
    structureFamily: "bicyclic",
    functionalClass: "hydrocarbon",
    formula: "C10H16",
    molecularWeight: 136.24,
    pubchemCid: 14896,
    casNumber: "127-91-3",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["pine", "woody", "green", "resinous"],
    naturalSources: ["Cannabis", "pine", "parsley", "basil"],
    cannabisOccurrence: "documented",
    cannabisContext: "Detected in cannabis and analytically distinct from α-pinene.",
    geneticsContext: "Pinene-producing synthases can be multiproduct enzymes, so measured chemistry remains essential.",
    cultivarContext: "Compare β-pinene directly rather than using a combined generic pinene bucket when the data support separation.",
    researchGuardrail: "Sensory and biological interpretations require evidence beyond a compound name.",
    viewNotes: {
      aroma: "Often described as pine-like, woody, green, or resinous.",
      chemistry: "A bicyclic C10 monoterpene hydrocarbon and structural isomer of α-pinene.",
      biosynthesis: "Formed from GPP through terpene-synthase cyclization.",
      genetics: "Synthase function should be validated experimentally rather than inferred only from sequence labels.",
      cultivars: "Retain the separate analyte when building cultivar fingerprints.",
    },
    sourceIds: ["THC-V13", "PUBCHEM"],
  },
  {
    slug: "terpinolene",
    name: "Terpinolene",
    aliases: ["terpinolene"],
    terpeneClass: "monoterpene",
    structureFamily: "monocyclic",
    functionalClass: "hydrocarbon",
    formula: "C10H16",
    molecularWeight: 136.24,
    pubchemCid: 11463,
    casNumber: "586-62-9",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["herbal", "fresh", "pine", "floral"],
    naturalSources: ["Cannabis", "tea tree", "nutmeg", "apple"],
    cannabisOccurrence: "documented",
    cannabisContext: "A variable cannabis monoterpene that may be minor in some profiles and prominent in others.",
    geneticsContext: "Terpinolene belongs to a multiproduct terpene-synthase context, so enzyme expression and product mixtures matter.",
    cultivarContext: "Low or high abundance should be established from representative sample sets, not one COA.",
    researchGuardrail: "Low concentration does not automatically mean low sensory relevance; odor thresholds and mixtures matter.",
    viewNotes: {
      aroma: "Common descriptors span herbal, fresh, pine-like, and floral notes.",
      chemistry: "A monocyclic C10 monoterpene hydrocarbon.",
      biosynthesis: "Produced from GPP through terpene-synthase reactions.",
      genetics: "May appear as one member of a multi-compound product spectrum.",
      cultivars: "Useful for chemovar fingerprinting when consistently measured across repeated samples.",
    },
    sourceIds: ["THC-V13", "PUBCHEM"],
  },
  {
    slug: "linalool",
    name: "Linalool",
    aliases: ["linalool"],
    terpeneClass: "monoterpene",
    structureFamily: "acyclic",
    functionalClass: "alcohol / oxygenated terpenoid",
    formula: "C10H18O",
    molecularWeight: 154.25,
    pubchemCid: 6549,
    casNumber: "78-70-6",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["floral", "sweet", "lavender-like", "fresh"],
    naturalSources: ["Cannabis", "lavender", "coriander", "basil"],
    cannabisOccurrence: "documented",
    cannabisContext: "An oxygenated monoterpenoid detected in some cannabis profiles. Stereochemistry, oxidation, drying, and storage can change measured composition.",
    geneticsContext: "Can arise through dedicated synthase activity and related terpene pathways; final abundance still depends on tissue and environment.",
    cultivarContext: "Use actual analytical profiles and record whether the method resolves stereoisomers.",
    researchGuardrail: "A floral aroma does not prove linalool dominance or a particular physiological effect.",
    viewNotes: {
      aroma: "Floral and lavender-like descriptors are common, but not exclusive.",
      chemistry: "An acyclic oxygenated monoterpenoid alcohol rather than a pure hydrocarbon terpene.",
      biosynthesis: "Produced from the monoterpene precursor pool with oxygenated chemistry influencing final identity.",
      genetics: "Synthase activity and stereochemistry matter when linking genotype to aroma.",
      cultivars: "Method details are important because routine panels may not resolve stereochemical forms.",
    },
    sourceIds: ["THC-V13", "PUBCHEM"],
  },
  {
    slug: "beta-caryophyllene",
    name: "β-Caryophyllene",
    aliases: ["caryophyllene", "beta-caryophyllene"],
    terpeneClass: "sesquiterpene",
    structureFamily: "bicyclic",
    functionalClass: "hydrocarbon",
    formula: "C15H24",
    molecularWeight: 204.36,
    pubchemCid: 5281515,
    casNumber: "87-44-5",
    biosyntheticPrecursor: "Farnesyl diphosphate (FPP)",
    aromaDescriptors: ["pepper", "spice", "woody", "dry"],
    naturalSources: ["Cannabis", "black pepper", "clove", "hops"],
    cannabisOccurrence: "documented",
    cannabisContext: "A common cannabis sesquiterpene that can persist relatively well as lighter monoterpenes are lost during handling and storage.",
    geneticsContext: "Functionally characterized cannabis synthases can produce β-caryophyllene, sometimes with α-humulene as a coproduct.",
    cultivarContext: "Interpret relative percentage carefully: it can rise after harvest simply because more volatile compounds declined.",
    researchGuardrail: "Receptor or health research should be displayed with study type and evidence strength, not converted into a medical promise.",
    viewNotes: {
      aroma: "Peppery, spicy, dry, and woody descriptors are common.",
      chemistry: "A bicyclic C15 sesquiterpene hydrocarbon.",
      biosynthesis: "Produced from FPP through sesquiterpene synthases.",
      genetics: "Caryophyllene-producing synthases can also produce other compounds such as humulene.",
      cultivars: "Absolute concentration is more informative than relative percentage alone when post-harvest loss differs.",
    },
    sourceIds: ["THC-V13", "PUBCHEM"],
  },
  {
    slug: "alpha-humulene",
    name: "α-Humulene",
    aliases: ["humulene", "alpha-humulene"],
    terpeneClass: "sesquiterpene",
    structureFamily: "monocyclic",
    functionalClass: "hydrocarbon",
    formula: "C15H24",
    molecularWeight: 204.36,
    pubchemCid: 5281520,
    casNumber: "6753-98-6",
    biosyntheticPrecursor: "Farnesyl diphosphate (FPP)",
    aromaDescriptors: ["woody", "herbal", "hoppy", "earthy"],
    naturalSources: ["Cannabis", "hops", "sage", "ginseng"],
    cannabisOccurrence: "documented",
    cannabisContext: "A cannabis sesquiterpene often discussed alongside β-caryophyllene but analytically distinct.",
    geneticsContext: "Can be a coproduct of caryophyllene-associated synthase activity.",
    cultivarContext: "Track humulene independently in cultivar fingerprints rather than collapsing it into caryophyllene.",
    researchGuardrail: "Co-occurrence with another terpene does not demonstrate a biological interaction.",
    viewNotes: {
      aroma: "Often described as woody, herbal, earthy, or hop-like.",
      chemistry: "A monocyclic C15 sesquiterpene hydrocarbon.",
      biosynthesis: "Derived from FPP in the sesquiterpene branch.",
      genetics: "Frequently linked to multiproduct synthases, including caryophyllene-associated enzymes.",
      cultivars: "Best treated as its own analyte in repeated sample comparisons.",
    },
    sourceIds: ["THC-V13", "PUBCHEM"],
  },
  {
    slug: "e-beta-ocimene",
    name: "(E)-β-Ocimene",
    aliases: ["trans-beta-ocimene", "(3E)-beta-ocimene", "e-beta-ocimene"],
    terpeneClass: "monoterpene",
    structureFamily: "acyclic",
    functionalClass: "hydrocarbon",
    formula: "C10H16",
    molecularWeight: 136.23,
    pubchemCid: 5281553,
    casNumber: "3779-61-1",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["citrus", "tropical"],
    naturalSources: [],
    cannabisOccurrence: "documented",
    cannabisContext: "Functionally characterized Cannabis sativa terpene synthase evidence establishes biochemical capacity to form (E)-β-ocimene. That enzyme evidence does not by itself establish universal flower occurrence or a fixed abundance.",
    geneticsContext: "CsTPS6FN from Finola was functionally characterized with (E)-β-ocimene as its major product. Final plant abundance still depends on genotype, expression, tissue, development, environment, and post-harvest handling.",
    cultivarContext: "Treat cultivar occurrence and abundance as measured sample evidence. Do not infer a permanent (E)-β-ocimene percentage from a cultivar name or from enzyme capability alone.",
    researchGuardrail: "Keep the (E) geometric isomer distinct from (Z)-β-ocimene and from unresolved or aggregate β-ocimene measurements. Enzyme capability is not a human-effect claim.",
    viewNotes: {
      aroma: "Reviewed Cannabis literature links trans/(E)-β-ocimene with citrus and tropical scent language; whole-flower aroma still reflects mixtures and thresholds.",
      chemistry: "An acyclic C10 monoterpene hydrocarbon with defined (3E) double-bond geometry.",
      biosynthesis: "Produced from the GPP monoterpene precursor pool through terpene-synthase activity.",
      genetics: "Cannabis CsTPS6FN provides source-verified functional evidence for (E)-β-ocimene production.",
      cultivars: "Use measured, isomer-aware laboratory data when comparing cultivar profiles.",
    },
    sourceIds: ["PUBCHEM", "BOOTH-2017-TPS"],
  },
  {
    slug: "z-beta-ocimene",
    name: "(Z)-β-Ocimene",
    aliases: ["cis-beta-ocimene", "(3Z)-beta-ocimene", "z-beta-ocimene"],
    terpeneClass: "monoterpene",
    structureFamily: "acyclic",
    functionalClass: "hydrocarbon",
    formula: "C10H16",
    molecularWeight: 136.23,
    pubchemCid: 5320250,
    casNumber: "3338-55-4",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["citrus", "tropical"],
    naturalSources: [],
    cannabisOccurrence: "documented",
    cannabisContext: "Functionally characterized Cannabis sativa terpene synthase evidence establishes biochemical capacity to form (Z)-β-ocimene. That result should not be converted into universal flower occurrence or fixed abundance.",
    geneticsContext: "CsTPS13PK from Purple Kush was functionally characterized with (Z)-β-ocimene as its major product. Enzyme product capability and flower concentration remain separate evidence questions.",
    cultivarContext: "Preserve the geometric isomer when the analytical method resolves it. Aggregate β-ocimene measurements should not be silently assigned to the (Z) form.",
    researchGuardrail: "Keep (Z)-β-ocimene distinct from the (E) isomer and from unresolved β-ocimene. Do not infer human effects from occurrence or enzyme data.",
    viewNotes: {
      aroma: "Reviewed Cannabis literature links cis/(Z)-β-ocimene with citrus and tropical scent language; whole-flower aroma still reflects mixtures and thresholds.",
      chemistry: "An acyclic C10 monoterpene hydrocarbon with defined (3Z) double-bond geometry.",
      biosynthesis: "Produced from the GPP monoterpene precursor pool through terpene-synthase activity.",
      genetics: "Cannabis CsTPS13PK provides source-verified functional evidence for (Z)-β-ocimene production.",
      cultivars: "Use measured, isomer-aware laboratory data rather than collapsing all ocimene signals into one identity.",
    },
    sourceIds: ["PUBCHEM", "BOOTH-2017-TPS"],
  },
  {
    slug: "alpha-terpinene",
    name: "α-Terpinene",
    aliases: ["alpha-terpinene", "p-mentha-1,3-diene"],
    terpeneClass: "monoterpene",
    structureFamily: "monocyclic",
    functionalClass: "hydrocarbon / cyclohexadiene",
    formula: "C10H16",
    molecularWeight: 136.23,
    pubchemCid: 7462,
    casNumber: "99-86-5",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["woody"],
    naturalSources: [],
    cannabisOccurrence: "documented",
    cannabisContext: "Cannabis terpene-synthase functional evidence supports biochemical formation of α-terpinene. This does not establish that every cultivar contains measurable α-terpinene.",
    geneticsContext: "CsTPS33PK from Purple Kush was functionally characterized with α-terpinene and γ-terpinene among its major products, demonstrating a multiproduct synthase context.",
    cultivarContext: "Keep α-terpinene separate from γ-terpinene and other terpinene isomers in analytical comparisons whenever the method permits.",
    researchGuardrail: "A TPS product assignment supports enzyme capability, not a guaranteed cultivar concentration or a biological effect.",
    viewNotes: {
      aroma: "Reviewed Cannabis literature includes a woody descriptor for α-terpinene; this does not make it a one-compound explanation of flower aroma.",
      chemistry: "A monocyclic C10 monoterpene hydrocarbon and cyclohexadiene isomer.",
      biosynthesis: "Formed from the GPP monoterpene pool through terpene-synthase cyclization/rearrangement chemistry.",
      genetics: "Cannabis CsTPS33PK provides source-verified functional evidence and also produces γ-terpinene, illustrating multiproduct enzyme behavior.",
      cultivars: "Use analyte-specific measured chemistry rather than a generic terpinene bucket.",
    },
    sourceIds: ["PUBCHEM", "BOOTH-2017-TPS"],
  },
  {
    slug: "gamma-terpinene",
    name: "γ-Terpinene",
    aliases: ["gamma-terpinene", "p-mentha-1,4-diene"],
    terpeneClass: "monoterpene",
    structureFamily: "monocyclic",
    functionalClass: "hydrocarbon / cyclohexadiene",
    formula: "C10H16",
    molecularWeight: 136.23,
    pubchemCid: 7461,
    casNumber: "99-85-4",
    biosyntheticPrecursor: "Geranyl diphosphate (GPP)",
    aromaDescriptors: ["citrus"],
    naturalSources: [],
    cannabisOccurrence: "documented",
    cannabisContext: "Cannabis terpene-synthase functional evidence supports biochemical formation of γ-terpinene. That capability should not be mistaken for universal measured flower occurrence.",
    geneticsContext: "CsTPS33PK from Purple Kush was functionally characterized with γ-terpinene and α-terpinene among its major products, placing both in a multiproduct enzyme context.",
    cultivarContext: "Keep γ-terpinene separate from α-terpinene and other structural isomers when analytical resolution allows.",
    researchGuardrail: "Enzyme capability, plant abundance, sensory contribution, and biological effects are separate evidence layers.",
    viewNotes: {
      aroma: "Reviewed Cannabis literature includes a citrus descriptor for γ-terpinene; this does not make it a one-compound explanation of flower aroma.",
      chemistry: "A monocyclic C10 monoterpene hydrocarbon and cyclohexadiene isomer.",
      biosynthesis: "Formed from the GPP monoterpene pool through terpene-synthase chemistry.",
      genetics: "Cannabis CsTPS33PK provides source-verified functional evidence and demonstrates a shared multiproduct context with α-terpinene.",
      cultivars: "Use analyte-specific repeated measurements rather than inferring γ-terpinene from a cultivar label.",
    },
    sourceIds: ["PUBCHEM", "BOOTH-2017-TPS"],
  },
  {
    slug: "squalene",
    name: "Squalene",
    aliases: ["squalene"],
    terpeneClass: "triterpene",
    structureFamily: "acyclic",
    functionalClass: "hydrocarbon",
    formula: "C30H50",
    molecularWeight: 410.73,
    pubchemCid: 638072,
    casNumber: "111-02-4",
    biosyntheticPrecursor: "Farnesyl diphosphate-derived triterpene pathway",
    aromaDescriptors: [],
    naturalSources: ["olive oil", "amaranth", "many eukaryotes"],
    cannabisOccurrence: "not-mapped",
    cannabisContext: "Included as a global terpene-family reference. This curated seed dataset does not currently assert a cannabis occurrence record.",
    geneticsContext: "Useful for teaching how terpene chemistry extends far beyond volatile C10 and C15 aroma compounds.",
    cultivarContext: "Excluded from cannabis cultivar matching until a qualified occurrence dataset is linked.",
    researchGuardrail: "Not-mapped means not established in this dataset; it is not a universal absence claim.",
    viewNotes: {
      aroma: "Not presented here as a cannabis aroma driver.",
      chemistry: "An acyclic C30 triterpene hydrocarbon.",
      biosynthesis: "Connected to the triterpene and sterol biosynthetic network.",
      genetics: "Demonstrates the broader scale of isoprenoid biosynthesis beyond volatile terpene synthases.",
      cultivars: "Not used in cannabis cultivar matching in this seed release.",
    },
    sourceIds: ["PUBCHEM", "GLOBAL-SEED"],
  },
  {
    slug: "beta-carotene",
    name: "β-Carotene",
    aliases: ["beta-carotene"],
    terpeneClass: "tetraterpene",
    structureFamily: "polyene",
    functionalClass: "carotenoid / tetraterpenoid",
    formula: "C40H56",
    molecularWeight: 536.87,
    pubchemCid: 5280489,
    casNumber: "7235-40-7",
    biosyntheticPrecursor: "Geranylgeranyl diphosphate (GGPP)-derived carotenoid pathway",
    aromaDescriptors: [],
    naturalSources: ["carrot", "sweet potato", "leaf tissue"],
    cannabisOccurrence: "not-mapped",
    cannabisContext: "Included as a global tetraterpene-family reference rather than a cannabis volatile-profile claim.",
    geneticsContext: "Provides a bridge from terpene classification into carotenoid biosynthesis and plant pigmentation.",
    cultivarContext: "Not used for cannabis aroma-profile matching in this seed release.",
    researchGuardrail: "Do not confuse pigment-related tetraterpenoids with the volatile monoterpenes and sesquiterpenes commonly discussed in aroma panels.",
    viewNotes: {
      aroma: "This record is included for family coverage, not as a volatile aroma descriptor.",
      chemistry: "A C40 tetraterpenoid carotenoid with an extended conjugated polyene system.",
      biosynthesis: "Derived from GGPP through carotenoid biosynthesis.",
      genetics: "Connects terpene-family classification to pigment and photosynthetic accessory pathways.",
      cultivars: "Outside the current cannabis volatile cultivar-matching layer.",
    },
    sourceIds: ["PUBCHEM", "GLOBAL-SEED"],
  },
];

export const terpeneBySlug = new Map(terpeneSeedCompounds.map((compound) => [compound.slug, compound]));
