"use client";

import { useState } from "react";
import styles from "./AtlasConceptVisual.module.css";

type Point={id:string;label:string;detail:string};
type Spec={title:string;subtitle:string;points:Point[]};

const specs:Record<string,Spec>={
  "atlas-radicle-v1":{title:"Radicle emergence",subtitle:"The first visible root organ establishes early seedling polarity",points:[
    {id:"coat",label:"Seed coat opening",detail:"Internal swelling and embryo growth mechanically open the seed coat as germination progresses."},
    {id:"radicle",label:"Radicle",detail:"The embryonic root is typically the first organ to emerge and begins anchorage and water uptake."},
    {id:"gravity",label:"Root orientation",detail:"Gravitropic responses help direct early root growth while shoot tissues reorient toward light."},
    {id:"branch",label:"Early branching",detail:"Lateral root formation follows after primary root extension and increases explored substrate volume."},
    {id:"transition",label:"Seedling transition",detail:"Radicle emergence marks an important developmental transition but does not by itself guarantee a vigorous seedling."}]},
  "atlas-root-uptake-v1":{title:"Water & nutrient uptake",subtitle:"Root-zone supply, membrane transport and transpiration connect the substrate to the shoot",points:[
    {id:"solution",label:"Root-zone solution",detail:"Water and dissolved ions must be present in accessible pore spaces around active roots."},
    {id:"surface",label:"Root surface",detail:"Fine roots and root hairs increase contact area with the surrounding solution."},
    {id:"membrane",label:"Selective transport",detail:"Ion uptake across living cell membranes is regulated; ions do not simply flow freely into the vascular system."},
    {id:"xylem",label:"Toward xylem",detail:"Water and absorbed ions move across root tissues before entering the xylem stream."},
    {id:"demand",label:"Shoot demand",detail:"Transpiration and growth influence movement through the plant, so root supply and atmospheric demand must be interpreted together."}]},
  "atlas-stem-cross-section-v1":{title:"Stem cross-section",subtitle:"Simplified dicot stem organization from epidermis to pith",points:[
    {id:"epidermis",label:"Epidermis",detail:"The outer tissue protects the stem surface and interfaces with the environment."},
    {id:"cortex",label:"Cortex",detail:"Cortical tissues contribute storage, support and metabolism between the epidermis and vascular region."},
    {id:"phloem",label:"Phloem",detail:"Living vascular tissue distributes photosynthate and signaling molecules from sources toward sinks."},
    {id:"xylem",label:"Xylem",detail:"Lignified conductive tissues move water and dissolved mineral nutrients and contribute structural support."},
    {id:"pith",label:"Pith",detail:"Central parenchyma tissue occupies the inner stem region in young stems and can contribute storage and internal support."}]},
  "atlas-node-anatomy-v1":{title:"Node anatomy",subtitle:"Where leaves, branches and axillary buds connect to the main stem",points:[
    {id:"node",label:"Node",detail:"A node is the stem region where leaves and axillary structures attach."},
    {id:"internode",label:"Internode",detail:"The stem segment between adjacent nodes determines spacing between successive attachment points."},
    {id:"petiole",label:"Petiole",detail:"The petiole connects a leaf blade to the stem and contains vascular continuity with the node."},
    {id:"bud",label:"Axillary bud",detail:"Axillary buds form in the angle between leaf and stem and can develop into lateral shoots."},
    {id:"branch",label:"Branch origin",detail:"A lateral branch develops from an axillary meristem and establishes its own nodes and growing tip."}]},
  "atlas-pollination-response-v1":{title:"Pollination response",subtitle:"Successful fertilization redirects individual floral development toward seed formation",points:[
    {id:"stigma",label:"Stigma contact",detail:"Pollen contact with receptive stigmas is the first visible event, but contact alone does not confirm fertilization."},
    {id:"tube",label:"Pollen-tube growth",detail:"Compatible pollen can germinate and grow a tube toward an ovule."},
    {id:"fertilization",label:"Fertilization",detail:"Successful gamete fusion initiates embryo and seed development within the ovule."},
    {id:"seed",label:"Developing seed",detail:"The ovule enlarges as embryo and seed tissues develop inside the surrounding bract."},
    {id:"comparison",label:"Pollinated vs unpollinated",detail:"Pollinated flowers can show developmental changes, but whole-flower appearance should not be used as the sole proof of fertilization."}]},
  "atlas-rootzone-interaction-v1":{title:"Root-zone interaction",subtitle:"Moisture, oxygen, pH, EC, temperature and atmospheric demand operate as one system",points:[
    {id:"moisture",label:"Moisture",detail:"Water content controls supply while also affecting gas-filled pore space and root-zone oxygen diffusion."},
    {id:"oxygen",label:"Oxygen",detail:"Root respiration requires oxygen; saturation, compaction and high biological demand can reduce availability."},
    {id:"chemistry",label:"pH & EC",detail:"pH influences nutrient chemistry while EC reflects total ionic concentration; both depend on the measurement method and substrate context."},
    {id:"temperature",label:"Root temperature",detail:"Temperature affects root metabolism, membrane processes, gas solubility and microbial activity."},
    {id:"demand",label:"Atmospheric demand",detail:"Leaf transpiration demand changes how quickly water is drawn from the root zone, linking canopy conditions to root behavior."}]},
  "atlas-measurement-context-v1":{title:"Diagnostic measurement context",subtitle:"Put plant observations and measurements into one time-aligned record",points:[
    {id:"root",label:"Root-zone readings",detail:"Record moisture, pH and EC using a consistent method appropriate to the substrate."},
    {id:"air",label:"Air conditions",detail:"Temperature and relative humidity provide atmospheric context and allow vapor-pressure calculations."},
    {id:"light",label:"Light",detail:"PPFD and photoperiod help interpret canopy demand and location-specific stress patterns."},
    {id:"history",label:"Water/feed history",detail:"Recent irrigation volume, composition and timing often explain changes that a single snapshot cannot."},
    {id:"timeline",label:"Time alignment",detail:"Measurements are most useful when linked to symptom onset, progression and recent actions rather than stored as isolated numbers."}]}
};

function Radicle({selected}:{selected:string}){const stages=[0,1,2,3];return <svg viewBox="0 0 720 420" role="img" aria-label="Radicle emergence sequence"><rect width="720" height="420" rx="24" fill="#0d1c14"/>{stages.map((s,i)=>{const x=105+i*165;return <g key={i}><ellipse cx={x} cy="175" rx="58" ry="41" fill="#928064" stroke="#d8c69f" strokeWidth="4" className={selected==="coat"&&i===1?styles.emphasis:undefined}/>{i>0?<path d={`M${x+5} 195 Q${x+18} ${230+i*18} ${x+5} ${280+i*22}`} stroke="#e7dfc8" strokeWidth="9" fill="none" strokeLinecap="round" className={selected==="radicle"?styles.emphasis:undefined}/>:null}{i>1?<path d={`M${x+5} ${270+i*20} Q${x-30} ${300+i*18} ${x-50} ${325+i*15} M${x+8} ${280+i*18} Q${x+38} ${302+i*16} ${x+54} ${328+i*12}`} stroke="#d8caa9" strokeWidth="4" fill="none" className={selected==="branch"?styles.emphasis:undefined}/>:null}<text x={x-8} y="360" fill="#a8d6b2" fontSize="14">{i+1}</text></g>})}<g className={selected==="gravity"?styles.emphasis:undefined}><path d="M610 80 v90" stroke="#78b6d6" strokeWidth="5"/><path d="M610 170 l-12-18 h24z" fill="#78b6d6"/><text x="625" y="135" fill="#aad8eb" fontSize="14">gravity</text></g><g className={selected==="transition"?styles.emphasis:undefined}><path d="M520 122 Q560 70 602 82" stroke="#7db66b" strokeWidth="8" fill="none"/></g></svg>}
function RootUptake({selected}:{selected:string}){return <svg viewBox="0 0 720 420" role="img" aria-label="Water and nutrient uptake pathway"><rect width="720" height="420" rx="24" fill="#0d1c14"/><rect y="245" width="720" height="175" fill="#2b251d"/><g className={selected==="solution"?styles.emphasis:undefined}>{[0,1,2,3,4,5].map(i=><g key={i}><circle cx={80+i*75} cy={315+(i%2)*25} r="11" fill="#6dbbd8"/><circle cx={105+i*75} cy={290+(i%3)*18} r="8" fill="#d1a85e"/></g>)}</g><path d="M360 65 C350 150 352 250 360 385" stroke="#d8c7a5" strokeWidth="28" fill="none"/><g className={selected==="surface"?styles.emphasis:undefined}>{Array.from({length:12}).map((_,i)=><line key={i} x1="350" y1={255+i*9} x2={245-(i%2)*18} y2={245+i*10} stroke="#eee1c6" strokeWidth="2.5"/>)}</g><g className={selected==="membrane"?styles.emphasis:undefined}><ellipse cx="360" cy="286" rx="38" ry="82" fill="none" stroke="#9bd1a8" strokeWidth="5"/></g><g className={selected==="xylem"?styles.emphasis:undefined}><path d="M360 260 C390 210 408 150 420 95" stroke="#6db8d5" strokeWidth="8" fill="none"/><path d="M420 95 l-10 20 h20z" fill="#6db8d5"/></g><g className={selected==="demand"?styles.emphasis:undefined}><ellipse cx="465" cy="82" rx="92" ry="32" fill="#427d46"/><path d="M500 65 Q540 28 575 38" stroke="#8ac7df" strokeWidth="4" fill="none"/></g></svg>}
function StemSection({selected}:{selected:string}){return <svg viewBox="0 0 720 420" role="img" aria-label="Simplified cannabis stem cross section"><rect width="720" height="420" rx="24" fill="#0d1c14"/><g transform="translate(360 210)"><circle r="155" fill="#5c774e" stroke="#c4d39c" strokeWidth="12" className={selected==="epidermis"?styles.emphasis:undefined}/><circle r="128" fill="#7f935e" className={selected==="cortex"?styles.emphasis:undefined}/>{Array.from({length:12}).map((_,i)=>{const a=i*Math.PI*2/12;const x=Math.cos(a)*92;const y=Math.sin(a)*92;return <g key={i}><ellipse cx={x} cy={y} rx="22" ry="14" fill="#c59d66" transform={`rotate(${i*30} ${x} ${y})`} className={selected==="phloem"?styles.emphasis:undefined}/><ellipse cx={x*.82} cy={y*.82} rx="19" ry="12" fill="#7db0c5" transform={`rotate(${i*30} ${x*.82} ${y*.82})`} className={selected==="xylem"?styles.emphasis:undefined}/></g>})}<circle r="48" fill="#c7c08c" className={selected==="pith"?styles.emphasis:undefined}/></g></svg>}
function NodeAnatomy({selected}:{selected:string}){return <svg viewBox="0 0 720 420" role="img" aria-label="Cannabis node anatomy"><rect width="720" height="420" rx="24" fill="#0d1c14"/><line x1="360" y1="360" x2="360" y2="65" stroke="#66895d" strokeWidth="24" strokeLinecap="round"/><g className={selected==="node"?styles.emphasis:undefined}><circle cx="360" cy="220" r="25" fill="#95b276"/></g><g className={selected==="internode"?styles.emphasis:undefined}><path d="M392 100 V190 M392 250 V340" stroke="#d1b468" strokeWidth="6" strokeDasharray="9 7"/></g><g className={selected==="petiole"?styles.emphasis:undefined}><line x1="360" y1="220" x2="225" y2="155" stroke="#718f5d" strokeWidth="13"/><path d="M225 155 q-90 -35 -120 18 q92 48 120 -18" fill="#467d48"/></g><g className={selected==="bud"?styles.emphasis:undefined}><ellipse cx="398" cy="195" rx="17" ry="29" fill="#9dc777"/></g><g className={selected==="branch"?styles.emphasis:undefined}><path d="M380 215 Q465 165 540 112" stroke="#668b5c" strokeWidth="14" fill="none"/><circle cx="545" cy="108" r="18" fill="#87b66b"/></g></svg>}
function PollinationResponse({selected}:{selected:string}){return <svg viewBox="0 0 720 420" role="img" aria-label="Pollination response sequence"><rect width="720" height="420" rx="24" fill="#0d1c14"/><g transform="translate(170 0)"><ellipse cx="0" cy="240" rx="92" ry="105" fill="#667f4e" stroke="#a9bc7b" strokeWidth="4"/><g className={selected==="stigma"?styles.emphasis:undefined}><path d="M-15 160 Q-45 115 -58 85 M15 160 Q45 115 58 85" stroke="#e9edf1" strokeWidth="8" fill="none" strokeLinecap="round"/></g><g className={selected==="tube"?styles.emphasis:undefined}><circle cx="-57" cy="84" r="10" fill="#dec766"/><path d="M-57 94 Q-25 125 -5 190" stroke="#dec766" strokeWidth="4" fill="none"/></g></g><g transform="translate(520 0)"><ellipse cx="0" cy="240" rx="105" ry="118" fill="#6c8252" stroke="#afc27e" strokeWidth="4"/><g className={selected==="fertilization"?styles.emphasis:undefined}><circle cx="0" cy="220" r="25" fill="#d6bf72"/></g><g className={selected==="seed"?styles.emphasis:undefined}><ellipse cx="0" cy="245" rx="38" ry="50" fill="#99815f" stroke="#d4c095" strokeWidth="4"/></g></g><g className={selected==="comparison"?styles.emphasis:undefined}><text x="115" y="380" fill="#acd8b5" fontSize="15">unpollinated context</text><text x="460" y="380" fill="#acd8b5" fontSize="15">developing seed context</text></g></svg>}
function Rootzone({selected}:{selected:string}){const items=[{id:"moisture",x:105,y:110,t:"H₂O"},{id:"oxygen",x:250,y:85,t:"O₂"},{id:"chemistry",x:455,y:85,t:"pH / EC"},{id:"temperature",x:610,y:115,t:"TEMP"},{id:"demand",x:360,y:345,t:"CANOPY"}];return <svg viewBox="0 0 720 420" role="img" aria-label="Root zone interaction map"><rect width="720" height="420" rx="24" fill="#0d1c14"/><ellipse cx="360" cy="215" rx="115" ry="145" fill="#2a251e" stroke="#6f805c" strokeWidth="4"/><path d="M360 95 C350 160 350 235 360 340 M360 170 Q310 210 280 290 M360 190 Q415 225 445 300" stroke="#d5c5a6" strokeWidth="8" fill="none"/><circle cx="360" cy="210" r="38" fill="#244634"/><text x="333" y="216" fill="#cfe6d4" fontSize="13">ROOTS</text>{items.map(it=><g key={it.id} className={selected===it.id?styles.emphasis:undefined}><circle cx={it.x} cy={it.y} r="48" fill="#17382c" stroke="#78ad87" strokeWidth="3"/><text x={it.x-23} y={it.y+5} fill="#c9e4cf" fontSize="14">{it.t}</text><path d={`M${it.x} ${it.y+48} Q360 210 360 210`} stroke="#668f73" strokeWidth="3" fill="none" strokeDasharray="7 6"/></g>)}</svg>}
function Measurement({selected}:{selected:string}){const cards=[{id:"root",x:70,y:90,w:155,h:82,t:"ROOT ZONE",s:"moisture · pH · EC"},{id:"air",x:270,y:90,w:155,h:82,t:"AIR",s:"temp · RH · VPD"},{id:"light",x:470,y:90,w:155,h:82,t:"LIGHT",s:"PPFD · photoperiod"},{id:"history",x:170,y:235,w:170,h:82,t:"INPUT HISTORY",s:"water · feed · timing"},{id:"timeline",x:390,y:235,w:170,h:82,t:"TIMELINE",s:"onset · progression"}];return <svg viewBox="0 0 720 420" role="img" aria-label="Diagnostic measurement context dashboard"><rect width="720" height="420" rx="24" fill="#0d1c14"/>{cards.map(c=><g key={c.id} className={selected===c.id?styles.emphasis:undefined}><rect x={c.x} y={c.y} width={c.w} height={c.h} rx="14" fill="#1f3d2c" stroke="#6d9a79" strokeWidth="3"/><text x={c.x+16} y={c.y+30} fill="#d9eadc" fontSize="13">{c.t}</text><text x={c.x+16} y={c.y+56} fill="#99c3a4" fontSize="12">{c.s}</text></g>)}<path d="M150 180 Q350 210 360 220 M350 180 V220 M550 180 Q420 205 360 220 M255 235 Q300 220 350 220 M475 235 Q420 220 370 220" stroke="#618b6d" strokeWidth="3" fill="none"/><circle cx="360" cy="220" r="12" fill="#a9d4b2"/></svg>}
function Graphic({assetId,selected}:{assetId:string;selected:string}){if(assetId==="atlas-radicle-v1")return <Radicle selected={selected}/>;if(assetId==="atlas-root-uptake-v1")return <RootUptake selected={selected}/>;if(assetId==="atlas-stem-cross-section-v1")return <StemSection selected={selected}/>;if(assetId==="atlas-node-anatomy-v1")return <NodeAnatomy selected={selected}/>;if(assetId==="atlas-pollination-response-v1")return <PollinationResponse selected={selected}/>;if(assetId==="atlas-rootzone-interaction-v1")return <Rootzone selected={selected}/>;return <Measurement selected={selected}/>}
export function AtlasCoreStructureVisual({assetId}:{assetId:string}){const spec=specs[assetId];const[selected,setSelected]=useState(spec?.points[0]?.id??"");if(!spec)return null;const point=spec.points.find(item=>item.id===selected)??spec.points[0];return <div className={styles.shell}><div className={styles.heading}><div><p>Interactive academic visual</p><h2>{spec.title}</h2><span>{spec.subtitle}</span></div></div><div className={styles.graphic}><Graphic assetId={assetId} selected={selected}/></div><div className={styles.controls} aria-label={`${spec.title} concepts`}>{spec.points.map(item=><button key={item.id} type="button" className={item.id===selected?styles.active:undefined} onClick={()=>setSelected(item.id)}>{item.label}</button>)}</div><div className={styles.detail}><strong>{point.label}</strong><p>{point.detail}</p></div></div>}
